### PR TITLE
Install larger icon

### PR DESCRIPTION
**Pull request by City-busz**
Beside the 32x32 icon, install icons in more sizes.

### CODE REVIEW

**Review by tsujan — CHANGES_REQUESTED** [review]
Nowadays apps don't use the "pixmaps" folder. Either Screengrab's icon should be changed to SVG or we should (make and) add a bigger icon to `hicolor`.

**Comment by City-busz** [comment]
I modified my PR to put the icon into `/usr/share/icons/hicolor/72x72/apps`.

**Review by tsujan — COMMENTED** [review]
> I modified my PR to put the icon into /usr/share/icons/hicolor/72x72/apps.

Acceptable to me because I use the theme icon.

The 72-pixel icon would still be blurry in some places, especially with scale factors. Let's wait to see what other LXQt members think about it.

**Comment by City-busz** [comment]
I modified my PR to install icons in more standard sizes: 16x16, 48x48, 64x64

**Comment by tsujan** [comment]
I really think we should change the icon to SVG and get rid of size folders. Will propose 2 icons at https://github.com/lxqt/screengrab/issues/259

**Comment by City-busz** [comment]
Okay, an SVG icon would be fine for me.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/screengrab/pull/284.

**Pull request closed without merging**
