### PR TITLE
commented out and wrote a comment to the imho useless warning

### LINKED ISSUE #174: Typo in
daxsteway--2019-10-23-13-44-39

Note the typo in interface word. I saw this when executing the app from terminal and requested for new screenshot

### PR DESCRIPTION
**Pull request by agaida**
fixes #174

### CODE REVIEW

**Comment by agaida** [comment]
so i could drop the commented out part completly?

**Comment by tsujan** [comment]
Yes :)

**Comment by agaida** [comment]
ok, done

**Comment by tsujan** [comment]
Good.

**Pull request merged**
