### PR TITLE
translations: Use .yaml for .desktop translation

### PR DESCRIPTION
**Pull request by palinek**

### CODE REVIEW

**Comment by yan12125** [comment]
@palinek This PR seems to break compilation:
```
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3")
-- XCB[XCB]: Found component XCB
CMake Warning (dev) at /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:424 (message):
  The package name passed to `find_package_handle_standard_args` (XCB_XCB)
  does not match the name of the calling package (XCB).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindXCB.cmake:207 (find_package_handle_standard_args)
  cmake/FindXCB.cmake:226 (_xcb_handle_component)
  CMakeLists.txt:32 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found XCB_XCB: /usr/lib/libxcb.so 
-- XCB[SHAPE]: Found component SHAPE
CMake Warning (dev) at /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:424 (message):
  The package name passed to `find_package_handle_standard_args` (XCB_SHAPE)
  does not match the name of the calling package (XCB).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindXCB.cmake:207 (find_package_handle_standard_args)
  cmake/FindXCB.cmake:226 (_xcb_handle_component)
  CMakeLists.txt:32 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found XCB_SHAPE: /usr/lib/libxcb-shape.so 
-- XCB[XFIXES]: Found component XFIXES
CMake Warning (dev) at /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:424 (message):
  The package name passed to `find_package_handle_standard_args` (XCB_XFIXES)
  does not match the name of the calling package (XCB).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindXCB.cmake:207 (find_package_handle_standard_args)
  cmake/FindXCB.cmake:226 (_xcb_handle_component)
  CMakeLists.txt:32 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found XCB_XFIXES: /usr/lib/libxcb-xfixes.so 
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-shape.so;/usr/lib/libxcb-xfixes.so 
-- Found X11_XCB: /usr/lib/libX11-xcb.so 
-- Build type: Release
-- Install prefix: /usr
-- Library path: /usr/lib/screengrab
CMake Deprecation Warning at cmake/LXQtTranslateTs.cmake:59 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:75 (include)


-- Editing screenshots in external editor support: ON
-- Enable D-Bus notifications: ON
-- Use system Qxt Library:
-- Update source translation translations/*.ts files: OFF
-- Documentation directory: /usr/share/doc/screengrab
-- Generating localize ...
CMake Error at cmake/LXQtTranslateDesktop.cmake:62 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:165 (lxqt_translate_desktop)


CMake Error at cmake/LXQtTranslateDesktop.cmake:92 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:165 (lxqt_translate_desktop)


-- Configuring incomplete, errors occurred!
See also "/build/screengrab-git/src/build/CMakeFiles/CMakeOutput.log".
```

**Comment by stefonarch** [comment]
Second issue: many *.yaml file do not include the  empty string 
`Desktop Entry/Name: ""`

**Comment by palinek** [comment]
Sorry, I wasn't aware that screengrab isn't using the lxqt-build-tools package.  Fix -> #226

**Comment by yan12125** [comment]
Thanks!

**Pull request merged**
