### PR TITLE
Codestyle improvements

### PR DESCRIPTION
**Pull request by shlyakpavel**
Hello.
I have tried to update the code style to recommendations of new c++ standards (namely c++11). I really hope you enjoy it :)
Have a nice day!

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks! Keep up the good work!

Just one thing:

`QString` is usually `const QString& str` as an argument   (or `const QString &str` -- whichever matches the code style) when it is `const`. And the same for similar types.

**Comment by shlyakpavel** [comment]
Ok, I'll fix it in the next commit

**Comment by shlyakpavel** [comment]
I have done some extra analysis on the code
Check out this PR https://github.com/shlyakpavel/screengrab/pull/1
[This](https://github.com/lxqt/screengrab/blob/master/src/modules/uploader/imgur/uploader_imgur.cpp#L58) place seems very suspicious to me. Why is function parameter always set to "true"?

**Comment by shlyakpavel** [comment]
Gotcha
What about the PR above? Should I also merge it to my master? (so all the changes land here)

**Comment by agaida** [comment]
i would leave out the uploader code right now

**Comment by agaida** [comment]
Otherwise - changes in the uploader code don't do any harm :) @tsujan, what do you think? The other code seems to be fine.

**Comment by tsujan** [comment]
> Otherwise - changes in the uploader code don't do any harm :)

Right! The PR seem OK. So, if it also compiles well, GTM.

**Comment by agaida** [comment]
@shlyakpavel  please merge the PR in question

**Comment by agaida** [comment]
Compile, install, starts - and works. so GTM.

**Pull request merged**
