### PR TITLE
Improve Screen Area instructions

### PR DESCRIPTION
**Pull request by wxl**
* fix grammar
 * correct actions to use

Fixes lxqt/screengrab#161

### CODE REVIEW

**Comment by tsujan** [comment]
There's a problem in: "... Press Escape to exit the program."

Pressing `Esc` doesn't necessarily mean exiting but it does mean canceling the screen-area screenshot. So, IMO, it should be something like "... Press Escape to cancel."

**Comment by wxl** [comment]
I think that is what should happen, but it's not what happens. Maybe I should just make the change you say and create a new issue for *that* problem 🤣

**Comment by tsujan** [comment]
> I think that is what should happen

The quit shortcut can be customized by user. If it is set to `Esc`, it causes an app exit; otherwise, `Esc` will only cancel this kind of screenshot.

Since most users are familiar with `Esc`, you could remove it from the explanation to prevent ambiguity. After all, your goal is giving a correct info to the user in all possible cases.

**Comment by wxl** [comment]
I hadn't really noticed the configurability before. You can't exactly configure which key can cancel, but I see you can configure which key can quit and that defaults to Escape. So, agreed and revised.

**Comment by tsujan** [comment]
GTM

**Pull request merged**
