### PR TITLE
Cleanup CMakeLists.txt and complete AUTHORS

### PR DESCRIPTION
**Pull request by agaida**
Removed the tar $foo - we use git archive right now
Added missed contributors to AUTHORS

### CODE REVIEW

**Comment by tsujan** [comment]
GTM, although you added "Tsu Jan" to the list and his contribution has been very small so far.

**Comment by agaida** [comment]
git log | sort | uniq | grep Author :)

**Comment by agaida** [comment]
and if the amount of added lines would count i would not be allowed in any of the AUTHORS files - because it will take ten years or longer to add the amount of lines that i'm already deleted from the projects :D

**Comment by tsujan** [comment]
I have plans for screengrab (only if the time allows me) -- those 2 PRs were just a start. You might not believe me if I say I hadn't heard of "screengrab" but now, it's what I use.

**Comment by tsujan** [comment]
A preliminary  TODO list:

(1) IMHO, the config code needs a rewrite, although it works.
(2) Screenshots shouldn't be made bigger than their real sizes (when the window is resized).
(3) It may be better to iconify the window on closing it -- when the tray icon exists.
(4) Also, a resize grip may not be a bad idea. It might be possible to put the checkboxes inside the statusbar then... just a thought.

**Comment by agaida** [comment]
cool ideas - i learned about screengrab years ago - long before LXQt if i remember right. The only thing that sucks in the moment is that screengrab right now isn't cross platform anymore - it was one of the rare things that works with Windows fine too.

**Comment by tsujan** [comment]
It should work on Windows after some modifications -- oh, not by me; haven't had Windows for 14 years. See what I received today: https://github.com/tsujan/Kvantum/issues/199 . Qt is so powerful!

**Pull request merged**
