### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/lxqt-desktop/screengrab/) for LXQt Desktop/ScreenGrab.

### CODE REVIEW

**Comment by yan12125** [comment]
Gosh I seemed to mess things up. Hopefully my fix is correct. I was trying to address a request from a user Yitin:

>  please add chiness translete for ScreenGrab

But at the first time, added files are named `zh_Hans.ts` and `zh_Hant.ts` instead of `zh_CN.ts` and `zh_TW.ts`. So I change language codes of https://translate.lxqt-project.org/languages/zh_CN/ and https://translate.lxqt-project.org/languages/zh_TW/ from zh_Hans and zh_Hant to zh_CN and zh_TW, respectively.

Some related discussions: https://github.com/lxqt/lxqt/issues/1495#issuecomment-399775043, https://github.com/WeblateOrg/weblate/issues/2559

**Comment by stefonarch** [comment]
I blocked screemgrab atm. 
Strangely it says "2 files changed" but I see only one.
Note that you can remove those  files also in weblate directly, it will create an commit with no files and this can be resetted (if no other translations/commits are pending.
Usually I add the user to the "add new translations" group.

I eliminated some translations in weblate (pt_PT, some de_FOO which are not present and so they cannot be created anymore. Should we remove zh_HANT too? I've no idea what is really necessary for Cina and Taiwan. Same goes for all those spanish of South America...

**Comment by yan12125** [comment]
> Strangely it says "2 files changed" but I see only one.

Hmm I do see 2 files. Where did you see one?

> Note that you can remove those files also in weblate directly,

Yep I use weblate to remove them ;)

> Usually I add the user to the "add new translations" group.

Bad memory around the pt mess is still in my head lol. Maybe I will just grant the user with permissions in the future.

> Should we remove zh_HANT too?

Both should be kept. Actually they are quite different languages. For a native speaker of zh_TW, understanding zh_CN needs a little learning efforts and vice versa.

Mozilla maintain a list of Firefox translations, which might be useful: http://ftp.mozilla.org/pub/firefox/releases/latest/README.txt

> Same goes for all those spanish of South America...

I googled for some introductory articles. Seems the difference between Spanish in Spain and South America is smaller than zh_TW and zh_CN - speakers of one can understand another. Nevertheless, I'm fine if someone copies es_ES to another file with some modifications. Firefox provides also 4 Spainish translations.

**Comment by stefonarch** [comment]
Now I see 2 , maybe the morning was some cloudy in my mind.
I think we can merge this, in weblates screengrab I see no cinese translation.

**Comment by stefonarch** [comment]
There are 6 cinese available, but only "simplified" and "traditional" have translations in LXQt.

**Comment by yan12125** [comment]
> There are 6 cinese available

Simplified Chinese in Singapore is similiar to that in Malaysia or China with some slight differences. Traditional Chinese in Hong Kong is similiar  to that in Macau or Taiwan. Similiar to my opinions about various Spanish, I'm fine if someone adds more Chinese languages. Nobody did that probably because there is no strong need or lack of manpowers. The situation for Min Nan is more complex. There are a few competing writing systems [1]. If someone wants to add it, further discussions are needed on which writing system is better for Linux desktop. By the way, Min Nan in Taiwan, different provinces in China and other countries are slightly different, too.

On the other hand, the Pinyin variant is somewhat strange. As far as I know, Pinyin is used to inform pronounciation of Chinese characters (e.g., teaching or translating people's names). I have never see it being used as a daily writing language. It may be removed.

PS. I'm a native speaker of zh_TW. Most statements here are based my observation.

[1] https://en.wikipedia.org/wiki/Written_Hokkien

**Comment by stefonarch** [comment]
> 'm fine if someone adds more Chinese languages

It's only  possible to add one  those 6 atm.

**Comment by yan12125** [comment]
Hmm didn't know that. I don't think we will hit that limit in near future, either.

**Comment by stefonarch** [comment]
I think you got me wrong: in weblate one can add atm 6 different versions of cinesem(those 6 present), because others are not implemented, but they can be added  (or removed in admin -I removed for example pt_PT and de_CH and some others).

**Comment by yan12125** [comment]
Oh I see 😅

**Pull request merged**
