### PR TITLE
first draft, added screenshot

### PR DESCRIPTION
**Pull request by stefonarch**
I open that one lying around too long, didn't recheck all, probably something has be changed , maybe the screenshot can be removed too.

### CODE REVIEW

**Comment by tsujan** [comment]
> It works on Linux and Windows operating systems

Are we sure about Windows? Maybe, we should remove the above sentence and treat screengrab like other LXQt apps.

> [optional] Qxt Library > 0.6

I think this is a remnant of old times and can be removed.

**Comment by tsujan** [comment]
You had made a nice gray palette [here](https://user-images.githubusercontent.com/10681413/135841219-183d53fc-0f7d-4d7b-a1ba-29d39b4514c1.png). Since you used a dark palette for the screenshot of lximage-qt, I suggest your gray palette for this one. Just a suggestion; nothing more.

**Comment by tsujan** [comment]
It can't be used for taking a screenshot as clean as yours because it's only for a fullscreen shot. I mentioned it just for its fun.

**Comment by tsujan** [comment]
Is this forgotten?

**Comment by stefonarch** [comment]
It looks like that....

**Pull request merged**
