### PR TITLE
Used an SVG icon instead of blurry PNG icon

### PR DESCRIPTION
**Pull request by tsujan**
The SVG icon is optimized with regard to size and visibility.

Also, fixed the absence of app icon in notifications (this old problem was never reported).

Closes https://github.com/lxqt/screengrab/issues/259

### CODE REVIEW

**Comment by tsujan** [comment]
Any comment or, perhaps, objection? I ask because a part of it is about an icon. Although it's better that the original icon, I may be missing something.

**Comment by stefonarch** [comment]
It looks good to me, first I thought this issue is new, but I realized it's also on master: icon is mostly  invisible until screen is taken:



https://user-images.githubusercontent.com/10681413/145668902-62fb598f-b9a0-4b29-85fe-4982c5a0c7fe.mp4

**Comment by tsujan** [comment]
> icon is mostly invisible until screen is taken

The notification icon *was* invisible. The problem is fixed by this PR:

notification

Do you see something different?

**Comment by stefonarch** [comment]
My screencast (taken with master) was about the _status notifier icon_: it appears shortly as generic icon, then until a screenshot is taken it's invisible. Delay is some sec.

**Comment by tsujan** [comment]
> ... was about the status notifier icon:

OK. It isn't related to this PR (you use a theme icon) but to Status Notifier. I've seen it with GoldenDict but not with screengrab. It may be caused by how the app creates its tray icon in its code.

> The icon is vsibile in the popup now.

Thanks for the confirmation.

**Comment by tsujan** [comment]
@stefonarch 
So, can this be merged?

**Comment by stefonarch** [comment]
Sure.

**Pull request merged**
